# Generated by Django 3.2.4 on 2021-08-19 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Usernames can only contain letters (a-z), numbers (0-9), and periods (.).', regex='/^[a-z0-9]{1,30}$/')])),
            ],
        ),
    ]
