# Generated by Django 3.2.4 on 2021-08-19 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_community_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Community name must be Alphanumeric.', regex='^[a-zA-Z0-9]*$')]),
        ),
    ]
